[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tokensale = "4p4prbrjN1moKY3W2918t6VJYuAphGikE47ZpBVZYdcf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
